apiVersion: apps/v1
kind: Deployment
metadata:
  name: wormhole
  namespace: czlingo
spec:
  selector:
    matchLabels:
      app: wormhole
  replicas: 1
  template:
    metadata:
      labels: 
        app: wormhole
    spec:
      containers:
      - name: wormhole
        image: registry.cn-chengdu.aliyuncs.com/czlingo/wormhole:test
        ports: 
        - containerPort: 8080
        volumeMounts:
        - name: wormhole-config
          mountPath: /config
      resource:
    volumes:
      - name: wormhole-config
        configMap:
          name: wormhole-config
          items:
          - key: config.yaml
            path: config.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: wormhole
  namespace: czlingo
spec:
  type: NodePort
  selector:
    app: wormhole
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30001